# Generated by Django 4.2 on 2023-11-07 03:47

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('posts', '0003_alter_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imag',
            field=models.ImageField(default=' ', upload_to='posts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
